/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cjun' at '17-3-24 下午8:42' with Gradle 2.14.1
 *
 * @author cjun, @date 17-3-24 下午8:42
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
